### ISSUE TITLE
authentication.context is missing in index.d.ts

### ISSUE THREAD

**Issue by vulvulune** [HNeukermans/adal-ts#11]
Hello,

The index.d.ts looks like this:
`export * from './authentication';
export * from './adal.config';`

Is it possible to add `export * from './authentication.context'`?

Because in my typescript application using this library, I would like to have a variable of the type **AuthenticationContext**, but I can't import it.

Thanks

**Comment by HNeukermans** [comment]
The creation of AuthenticationContext is hidden on purpose.
Authentication is the facade. It is the root api of adal-ts. Authentication knows how to build the AuthenticationContext. This is on purpose because the context requires a lot of dependencies upon creation. 

Why would you want to import it directly?

**Comment by vulvulune** [comment]
I don't want to instantiate a new AuthenticationContext object, but just keep a variable on it, to access the getUser() and getToken() methods. 

In my typescript project, I can't have a variable of type AuthenticationContext, because the class is not exported. Currently my variable is of type "any", it's working but I loss the autocompletion when I use it.

When the methods getuser() and gettoken() will be out of the context, the issue will be resolved too.

**Comment by HNeukermans** [comment]
OK. Needs fix.

**Comment by HNeukermans** [comment]
should be fixed in 0.5.9-alpha1 release
